### ISSUE TITLE
[FEATURE] Get Project by url slug

### ISSUE THREAD

**Issue by Davoleo** [Mondanzo/mc-curseforge-api#14]
**Describe the solution you'd like**
It'd be cool to use url slugs along with project ids to request single identified projects
Here's what I'm talking about:
![image](https://user-images.githubusercontent.com/24458276/100540425-9a6a8c80-323d-11eb-8e60-234d04dfe73e.png)
![image](https://user-images.githubusercontent.com/24458276/100540438-a8201200-323d-11eb-96e1-c3aa26470007.png)

**Additional context**
I don't actually know if URL slugs are unique over different kind of projects (mod, modpacks, maps), so it could be a bit complex to do
while I'm sure project ids are unique in different kinds of projects as well

**Comment by Mondanzo** [comment]
The problem with this is, that the API from Curseforge isn't offering a way to grab a mod by its slug. It used to be possible but with the current API version from Curseforge it is not.

**Comment by Ephys** [comment]
Your best shot to get a project by its slug would be to crawl and store the pages of their search API, and to build your mapping on your end

If it's not overkill for your use case, you can start with https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&index=0&pageSize=100&sectionId=6&sort=0 which returns the list of minecraft mods (docs: https://twitchappapi.docs.apiary.io/#/reference/0/twitch-addon-search/twitch-addon-search/200?mc=reference%2F0%2Ftwitch-addon-search%2Ftwitch-addon-search%2F200)

**Comment by Davoleo** [comment]
I'll close this issue for now, as it's not implementable and honestly not a straight necessity
