### ISSUE TITLE
[BUG] Not really a bug

### ISSUE THREAD

**Issue by SkyNetCloud** [Mondanzo/mc-curseforge-api#19]
![image](https://user-images.githubusercontent.com/24949001/104338037-18b88080-54c4-11eb-9c12-5198dafcdae5.png)
Any chance you could fix this if not it's fine

**Comment by Mondanzo** [comment]
I'm not going to ask why you need this library in a music bot.
But I guess I can try to look into typescript declarations.

**Comment by SkyNetCloud** [comment]
I use the bot for other things besides music I was just too lazy to rename the folder it was in

**Comment by fractaal** [comment]
I actually created my own Typescript Definition files for this package because I was using it in a typescript project as well but I haven't really tested it thoroughly and haven't submitted it to the DefinitelyTyped repo, I could make a pull request with the type defs if you want

**Comment by SkyNetCloud** [comment]
that would be helpful 👍

**Comment by fractaal** [comment]
created pr @ #20 w/ typescript declarations

**Comment by Mondanzo** [comment]
Oh yeah I forgot to close this issue with e96b0e5

(btw @fractaal you should configure your GitHub client properly, so your commits are also getting counted for your account)
