### ISSUE TITLE
API doesn't seem to be updated with Curseforge?

### ISSUE THREAD

**Issue by fractaal** [Mondanzo/mc-curseforge-api#6]
Before anything else, I love this thing. It's (obviously) an integral part of my mod manager for curseforge and I love it to bits.

However, it doesn't seem to be up to date with Curseforge, in that when polling for mods supporting 1.15 and up it returns nothing, and some files returned by `newest_only` aren't actually the newest version available for the selected Minecraft version on Curseforge, I was just wondering why this is and what I might be able to do to contribute. :))

![image](https://user-images.githubusercontent.com/19900120/80111215-3189aa80-85b2-11ea-9ce6-6aaffb83ee21.png)

**Comment by Mondanzo** [comment]
The problem probably is that Curseforge disabled that api and thererfore it doesn't query the actual mods anymore. Therefore the thing to do now is find out if there's a new api url to use and sadly they aren't really into offering an api so it's going to require some investigating of the Twitch app with Wireshark or other tools. I'm going to check if I can find a new api url to (ab)use.

**Comment by fractaal** [comment]
The fact that they wont expose an API is just infuriating. The fact that I can't even access the API docs pisses me off even more

Isn't it possible that they've only changed the url and all the other API methods have remained the same? It might just be a matter of finding the new endpoint.
