### ISSUE TITLE
[BUG] getModDescription returns error

### ISSUE THREAD

**Issue by fractaal** [Mondanzo/mc-curseforge-api#8]
**Describe the bug**
this.getModDescription() returns error 
`unexpected token < in JSON at position 0 at JSON.parse`

**Example code to execute the bug**
Any code invoking the function causes this exception

**Expected behavior**
An HTML String is returned by the function.

**Screenshots**
![image](https://user-images.githubusercontent.com/19900120/80208212-50477a00-8662-11ea-9c81-810df549b015.png)

**Desktop (please complete the following information):**
 - Version v2.0.0
- Node Version v13.6.0

Bug is caused by innerGet immediately assuming all data sent to it is JSON and causes an exception when a string of HTML is what it gets

**Comment by Mondanzo** [comment]
Should be closed by #9 now.
